### ISSUE TITLE
Gui Scaling

### ISSUE THREAD

**Issue by makerimages** [Vswe/ModJam3#1]
This is what I see on fulscreen.
![2013-12-18_15 07 32](https://f.cloud.github.com/assets/5919890/1773374/8377906a-67e5-11e3-81ca-d4c830decc7e.png)

**Comment by Vswe** [comment]
That is a known problem. It's the same problem I use to have in Steve's Carts. I have the code to fix it but wasn't allowed to add it during ModJam. It will soon be fixed.

For now, change your GUI scale setting to make it work.

**Comment by Vswe** [comment]
Fixed in alpha 4
