### ISSUE TITLE
Block labeler

### ISSUE THREAD

**Issue by Vswe** [Vswe/ModJam3#13]
Item used to select or label blocks in the world to be able to automatically select them in the manager (when selecting inventories, tanks or emitters) or at least show labels there to allow you to know which blocks you labeled. However, I'm not entirely sure how this should be implemented from a user point of view. Any suggestions?

**Comment by ghost** [comment]
Hmm...  something like these maybe?
![label](https://f.cloud.github.com/assets/6279568/1900424/d4e44a6c-7c51-11e3-9dd3-480dfead12bc.png)
![gui](https://f.cloud.github.com/assets/6279568/1900425/dc0b773e-7c51-11e3-9485-99ef53057cae.png)

**Comment by DasCleverle** [comment]
Couldn't just use the name of a chest when it's renamed in an anvil. And then  show it like above in brackets.

**Comment by Vswe** [comment]
The problem with the named chests (etc) is that the names aren't syncronized properly to the client side and some inventories (non-vanilla) don't support it.

Wouldn't the requirements of placing signs be annoying, or do people usually place signs like that?

**Comment by ghost** [comment]
Maybe a functionality like name tags but the names stored in the manager

**Comment by SomewhatDamaged** [comment]
Could such name tags be stored in NBT, require a tool to place on them (or remove) and, with that tool in hand, allow you to see the name? Then the manager could read the tags from chests as they are placed on the network. Perhaps allow this for mod-based IO units so you can name redstone emitters and such as well?

**Comment by DrSilix** [comment]
first thing i think of is the LogisticsPipes HUD glasses which render a GUI in 3D space. maybe something along those lines but just for names, possibly could be expanded upon too.

**Comment by SomewhatDamaged** [comment]
A lot of mods are using the wrench they come with to do such things (showing hidden paths). Perhaps the cable itself could be used? Right click (and use up) one cable on an inventory block to add a name to it. Then if you look at it with one in your hand you can see the name/remove/rename it.

**Comment by Xuerian** [comment]
SomewhatDamaged is on to something important, here. A specific tool that supplied more information and allowed tagging, etc would be super handy and seems the appropriate thing to do at this point. (Something worth seeing yet another wrench added)

**Comment by Vswe** [comment]
I hate tools like that. If you build something using multiple mods you might be using a wrench, a screwdriver and something else. That way you are forced to use one third of your items in your hot-bar just because the mods haven't implemented anything better.

**Comment by Xuerian** [comment]
I don't like having 15 wrenches in the first place, but there's something to be said for one actually providing more value than "Can rotate and dismantle blocks". 

But if you've got something better, then hey presto. 

The labeling thing is a big deal though, especially when dealing with lots of storage buffer tanks and nondescript chests, as well as inventory relays. 

Maybe a mode you can toggle with the manager block, showing you active inventory cabling paths, connected inventories, and letting you label them? Lots of extra rendering stuff I'd imagine, but a in-world solution, and no wrench.

**Comment by SomewhatDamaged** [comment]
Hence why I suggested have the cable, which has no other need to interact with chests, accomplish this.

**Comment by ghost** [comment]
Maybe some sort of upgrade for the cable connected to the block that needs
to be named

**Comment by SomewhatDamaged** [comment]
Or, failing a world tool, what about just an option in the interface to name chests/emitters/etc?

After having watched your latest video and seeing you interact with the adv inventory unit gave me an idea. Why not allow a right click on the cable (regular cable, or even an advanced one) that allows you to name adjacent inventories?

**Comment by esotericist** [comment]
I'd like to throw in support for right-click-on-cable to be able to set names. It'd be nice if the UI showed all valid containers (as SFM knows them) connected to that specific cable, then permitted naming them separately.

Objects which have both an inventory and a tank could possibly have those listed separately, to be named separately.

**Comment by SomewhatDamaged** [comment]
Well, with variables and being able to name elements this is almost a redundant idea. Almost.

**Comment by esotericist** [comment]
I do not concur. If you're dealing with a large number of similar machines, being able to pre-name things before you sit down to deal with the nodes would be extremely helpful, particularly without having to remember coordinates.

It would also potentially assist with save/load configurations; if you name things consistently at the cable/machine level, a copied SFM configuration could work 'out of the box'.

**Comment by Aexoyir** [comment]
I've left a suggestion that would help with this, allowing you to identify inventories based on their contents, but I like the idea of being able to activate a basic UI on a cable and rename objects directly connected to said cable also. One thing to consider is that any mod items that take up a full block may make it difficult to get TO the cable to name the item...

**Comment by chainingsolid** [comment]
I had an idea, an item that lets you click on blocks and name them and save that name to the items NBT data , then put that item in the managers GUI to allow it to use those names provided on the tooltips on the GUI

**Comment by Vswe** [comment]
I've figured out how to do this now. It's a bit strange and a bit tricky to explain. So I'll give you a screenshot in a few days.

**Comment by Vswe** [comment]
This issue has finally been vanquished! :D https://www.youtube.com/watch?v=XN-XQtmu4d8

**Comment by Xuerian** [comment]
Well. That certainly improves initial set up, I suppose! Especially with the sign option. Awesome.

Only one request left, and you sortof mentioned it. Could you show the text of the attached sign in the main tooltip directly? That would just eliminate the second mouseover in case of sign labeling. 

If there's more than one sign there's no reason to bother with anything fancy, just pick one at random or whatever and show it. That way if we attach one sign, we get a label. Like you said, nothing special, no marker blocks or tools.
