### ISSUE TITLE
GUI Labels

### ISSUE THREAD

**Issue by naab007** [Vswe/ModJam3#14]
It would be very nice to be able to attach labels to different stuff in the GUI.

It tends to get really confusing when you have like 20-30 functions on one block so it would be really nice if you could link a label to say a trigger to keep track of what it does.

**Comment by Vswe** [comment]
With the ability of renaming components (issue #9), would this still be necessary?

**Comment by naab007** [comment]
depends, do you see it directly without the need to click on the command?

**Comment by Vswe** [comment]
Yeah.

**Comment by naab007** [comment]
Then I guess not.
