### ISSUE TITLE
Input Node Duplication Bug

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#15]
1. place down an inventory manager with a chest on the left and right
2. create a trigger set to interval
3. create 2+ inputs inline pulling from the inventory to the left
4. create an output inline to the right inventory
5. create an input inline pulling from the right inventory blacklist
6. create an output inline pushing back to the left inventory
7. fill the left chest with 64+ of an item

result: the stack of 64 of the item in the left inventory will be added to the buffer multiple times without cost then output to the right inventory and will then be moved back to the left. this will work as long as there is a stack of the item in the left inventory

expected result: the input node should take into account what has been pulled out of an inventory by any previous input nodes.

**Comment by Vswe** [comment]
Fixed in alpha 26.
