### ISSUE TITLE
Sides when dealing with multiple targets

### ISSUE THREAD

**Issue by SomewhatDamaged** [Vswe/ModJam3#18]
When trying to check multiple targets, you cannot select a a different side for each.

Example, trying to say I want a redstone condition to be true on the north side of one receiver and the south side of another, but no other sides.

**Comment by Vswe** [comment]
That's never going to happen, if you want different settings for the different selected blocks you will have to add multiple commands. Allowing you to configure it differently wouldn't be possible interface wise.
