### ISSUE TITLE
Logical operators

### ISSUE THREAD

**Issue by SomewhatDamaged** [Vswe/ModJam3#19]
Any chance we could have a generic 'logical' unit that would have drop downs for specific logic types (and, or, xor, nand, etc)?

Perhaps integrate such into the Flow Control?

**Comment by Vswe** [comment]
Where would these logical operators be? What would be the input?

**Comment by Vswe** [comment]
Unless I get some more information about this I have to close it as invalid.

**Comment by SomewhatDamaged** [comment]
Okay, I am not the best of artists, but will try and do a mock-up of what it would look like.

**Comment by SomewhatDamaged** [comment]
![logic option](https://f.cloud.github.com/assets/6394544/2003988/7dcb2190-868a-11e3-90e6-595bf311f483.jpg)

This would be the option in flow control that unlocks the logic gates.

Then, once selected, a new option set is shown with the logic operators offered (these are just some examples, could even perhaps offer it in a drop down). Note, you could leave some out. For example a NAND gate with one input is a NOT gate, etc.

![or gate](https://f.cloud.github.com/assets/6394544/2003995/0b73830c-868b-11e3-8e86-1d9a77cb97d2.jpg)

**Comment by Vswe** [comment]
But the input pins do not contain a boolean value, and what would the output pin do.

**Comment by SomewhatDamaged** [comment]
The pulses from a trigger, whether fed through a condition or not, would be boolean, correct? That was what I was trying to get at manipulating, the clock/condition signals. Perhaps there would be a better way to do it than via a flow block however.

**Comment by Vswe** [comment]
Pulses are never boolean.
