### ISSUE TITLE
Odd interaction with Factorization Packagers

### ISSUE THREAD

**Issue by esotericist** [Vswe/ModJam3#21]
When SFM inserts objects into a Factorization Packager, the packager fails to notice until some kind of user edit of the inventory takes place, such as right clicking the stack to pick up half of it or adding more by hand. At this point the packager will function correctly until it's empty. Afterwards, any new stack added by SFM will exhibit the problematic behavior, again until the stack is interacted with.

This problem does not happen when inserting into the packager using pipes, itemducts, etc.

**Comment by Vswe** [comment]
Fixed in alpha 29.
