### ISSUE TITLE
Liquid conditions appear to be not functioning

### ISSUE THREAD

**Issue by esotericist** [Vswe/ModJam3#22]
I set up SFM with connectivity to a tank and a redstone emitter. Intent: Be able to emit a redstone signal based on presence or absence of lava.

If I connect an interval trigger directly to the emitter command, the emitter works as expected.

If I connect the interval to a Liquid Condition first, the emitter will never be triggered, regardless of which output pin is used on the condition.

Configuration for condition:

![tank configuration](https://f.cloud.github.com/assets/1569754/1927571/a37c18aa-7e5f-11e3-9114-cbd0f177dad9.png)

(tested with: Tinker's Construct smeltery tank, Thermal Expansion portable tank

**Comment by Vswe** [comment]
Fixed in alpha 25
