### ISSUE TITLE
Redstone emitter pulse doesn't pulse

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#24]
1. drop a manager and a redstone emitter
2. set up a trigger connected to an emitter node set to pulse

result: redstone emitter turns on a stays on

**Comment by esotericist** [comment]
Did you wire up the emitter to the trigger before setting it to pulse? I've gotten tripped up by this a few times.

**Comment by Vswe** [comment]
Fixed in alpha 29 (the bug was introduced in alpha 27).
