### ISSUE TITLE
Input Node whitelist does not respect minimum specified amount

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#27]
When transferring items from an inventory an amount of items less than the number specified in the input white list can be moved.  the previous behavior when the contents of the inventory had to be greater than the specified white list amount and only then would the specified amount be moved.

example of previous/intended behavior:
white list set to 8 sugar on an input node
if 3 sugar put into chest nothing would happen
if 8 sugar would be put into chest 8 sugar would be moved
if 12 sugar would be put into chest 8 sugar would be moved and 4 would stay until 4 more were received

if this is not the intended behavior may i request that an option be added to allow this sort of behavior

**Comment by Vswe** [comment]
This is indeed intended behavior. If you wish to check if you have 8 items, set up a condition that checks for those 8 items before your item are being moved.
