### ISSUE TITLE
Crash on selecting gold nugget in Output item white list

### ISSUE THREAD

**Issue by esotericist** [Vswe/ModJam3#28]
Now that SFM gets along with packagers, I was setting up a logic set for packaging gold nuggets.

I used .inv to be able to click on the gold nugget in my inventory (more out of getting accustomed to the new feature more than a need to specify the gold nugget in particular), and when I clicked on it the client crashed.

There were no difficulties specifying several other items, specifically all TiCo oreberries, and aluminum nuggets.

Crash report is here:
http://pastebin.com/2gWbNpYW

**Comment by Vswe** [comment]
It has nothing to do with the item actually. Basically what's happening is that you click through to the arrows for changing fuzzy mode, and it crashes. I derped and forgot to check if the edit menu was open. Fix will be released shortely.

**Comment by Vswe** [comment]
Fixed in alpha 32.
