### ISSUE TITLE
Boolean variable along with boolean condition

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#33]
add in a true/false variable
add a condition that when provided an input will check a provided boolean variable and if true output.

the functionality of this suggestion can already be done with redstone emitters and emitter condition, however with the introduction of for loops and their inherent ability to process "stuff" during a tick, having a condition statement that does not rely on a full game tick happening may be beneficial.

**Comment by Vswe** [comment]
If this is the case, it's not intended. Emitters are supposed to turn on the next tick (to prevent infinite looping). However, the manager should be able to detect the currently detected values. Am I correct by assuming that a fix like that would fix what you need?

**Comment by DrSilix** [comment]
Yes most definately, if the manager would keep track of that it would be great, I guess i assumed that they were functioning correctly. I do think that a boolean variable/condition couldn't hurt though maybe in the future, especially when using alot of them. I'm just so excited there is a programming language inside of minecraft and it's done so well.
