### ISSUE TITLE
Inventory Manager's inactive on world load

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#35]
Machine Inventory Manager's are inactive upon world load until they are accessed with a right click

**Comment by Vswe** [comment]
I thought I fixed that.

**Comment by DrSilix** [comment]
me too i dunno I noticed it happening for the past 2 versions

**Comment by Vswe** [comment]
I fixed it a long time ago. I can't seem to reproduce it. Any help how to do it?

**Comment by Vswe** [comment]
Found it, it was the variables that wasn't loaded properly from their definition. It was the exact same error as I had with the inventories before. I'll push a new version right away.
