### ISSUE TITLE
Inventory Conditions -- 'requires none'

### ISSUE THREAD

**Issue by esotericist** [Vswe/ModJam3#36]
Currently, item and liquid conditions have the options 'requires all' and 'if any'. It'd be nice to have 'requires none' as a condition, as a type of blacklist. 

As it stands, there isn't currently a way in SFM to detect if an inventory is completely empty. The 'requires none' functionality would permit this, along with some other useful tricks.

**Comment by Vswe** [comment]
With the latest update you can simply look for any item. Then the condition will evaluate to false if the inventory is completely empty.
