### ISSUE TITLE
items can be pulled from the block gate without destroying the block - infinite item glitch

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#37]
I have found 2 separate ways to do this
1.(only vanilla and sfm)
lay down an inventory relay and put a block gate at it's head. place a block in front of the block gate and then place a hopper under the inventory relay. WALLA infinite items

2.(rotarycraft handheld vacuum)
put down a block gate and place a block in front of it, then use the handheld vacuum on the block gate to suck the items out of it. the block will not be broken.

i suspect these are the same issue just figured it's worth noting

**Comment by Vswe** [comment]
It had actually nothing to do with the Block Gate. It was purely an Inventory Relay issue. Thanks for reporting it. It has now been fixed.
