### ISSUE TITLE
Block Gates can interact with bedrock

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#38]
yep. you can farm bedrock which has really no use. due to not being able to move the block gate with a piston the final blocks leading to the void cannot be broken, however if you have a block moving mod such as redstone in motion a hole to the void can be opened.

**Comment by Vswe** [comment]
I'll take a look at it. Quickly farm some bedrock before I fix it! :P

**Comment by Vswe** [comment]
Fixed.
