### ISSUE TITLE
Inventory list and Item list suggestions

### ISSUE THREAD

**Issue by Aexoyir** [Vswe/ModJam3#44]
The purpose of this suggestion is that this allows you to identify an inventory by it's contents which is MUCH easier than identifying by it's location.

On the list of Inventories on an Input or Output marker, if you have only 1 inventory selected, the contents of said inventory shows up under the list of inventories. Here you can also select any item in the inventory (which would then be highlighted white) and that item would be put on the filter list.

If this proves to be resource intensive, you could show the 1st item from the inventory only and not make it clickable...
###### 

The purpose of this suggestion is to make preparing larger sorting systems easier.

On the list of inventories, make select All, select NONE, and INVERT selection buttons. If you select a variable that is local, the contents of said variable are selected in the list, this way, if you select a variable, then press invert, all inventories except those in the variables end up selected.
###### 

The purpose of this suggestion is to make preparing larger sorting systems easier.

An import button on the Filter section would import all items from all of the selected inventories.
![inventorieslist](https://f.cloud.github.com/assets/6588130/2080306/a9b2a49e-8dd4-11e3-9ff1-0d7486f445da.png)

**Comment by Vswe** [comment]
You assume all containers are inventories, which is far from the case with tanks, receivers, emitters and block detectors. Also, you assume that space is free to be used, the spot where you suggest the content search to be is already in use.

**Comment by Aexoyir** [comment]
So those items that have no inventory show nothing...
That spot is used when you have multiple items selected, that's why I mentioned it would be if you have ONLY one item selected...

Just a thought I had. You decide what of it is of value to you.

**Comment by Vswe** [comment]
I don't think this is a good implementation of a better selection system. However, a better selection system is a must and will be implemented. I think I have something in mind. It won't be item based, but rather location, variable and type based by using both search boxes and range options. It might sound a bit abstract and that's because I haven't decided exactly how it should work yet.
