### ISSUE TITLE
Crafting / Requesting block

### ISSUE THREAD

**Issue by Aexoyir** [Vswe/ModJam3#45]
The reasoning behind this block is that I think there should be REASON the manager can auto craft. Also a requesting system would be nice. And since this does both and allows you to craft PULLING items from your network... It seems to me to be worth putting it forward for you to mull over.

Typing shows a list matching your filter. These items can be click-dragged into the crafting grid or into the result box. Either way only a ghost image of the item is left. You can also do this with items from your inventory or NEI or TMI.

Clicking the RIGHT arrow loads the items from the inventories to which this table has been allowed access in the factory manager.

The number to the right of the completion box is how many you would like the crafting table to try to pull. 0 is MAX. The table needs to scan the network and come up with the Lowest Common Denominator and then pull that many multiples of the required items.

Clicking the LEFT arrow returns items remaining in the crafting grid to their inventories of origin. Any items whose origins are no longer available (such as full) will remain in the crafting grid. Any items placed in the crafting grid by the player remain in the crafting grid. As with a normal crafting table, any items in the grid upon exit are ejected into the world.

A stand-alone item in the manager (similar to a variable, no pins) is the Crafting Table. In this item you can define what items the table, when accessed by a player, can draw from. Here is also where you define who can click the LOAD ITEMS (RIGHT arrow) button. Anyone not on the list can still use the table as a Crafting Table but cannot load items.

This is also an item request system. You can search an item and put it in the grid, select a quantity, pull from inventories and then simply pull the items from the grid and put them into your inventory.

The Crafting Table can also be selected as an Input where it accepts a white-list of one item (of select-able quantity) and when pulled from, it will acquire the necessary items from the chests selected.

![craftingblock](https://f.cloud.github.com/assets/6588130/2095734/c9803e74-8eee-11e3-986c-1710b0e45219.png)

**Comment by Vswe** [comment]
This makes no sense whatsoever to me. This seems to go away from the way SFM works and it wouldn't give you any new features.

**Comment by Aexoyir** [comment]
This block would allow you to everything a crafting table would do but without having to go to EACH chest to get the ingredients first.

It also allows you to request a specific number of a specific item from any of the allowed places on demand.

The idea is to allow you to tap in to the network from a terminal of sorts.

**Comment by esotericist** [comment]
It sounds like you want AE.

**Comment by Vswe** [comment]
^ Indeed, this is not AE.

**Comment by Aexoyir** [comment]
Never used it...
