### ISSUE TITLE
Crash on adjusting flow control nodes in SMP

### ISSUE THREAD

**Issue by esotericist** [Vswe/ModJam3#46]
A few times today I was attempting to adjust a 'collector' flow control node from 2 pin to 5 pin, and this happened.

http://pastebin.com/SABT6DCG

I don't have the exact reproduction steps, because I didn't happen to record the process, I can't reproduce it locally in SSP, and folks have asked that I stop breaking the server.

**Comment by Vswe** [comment]
Which version are you using?

**Comment by esotericist** [comment]
Currently A52. Not currently in a position to push for the newest... and as I said, I couldn't duplicate it locally, so I couldn't see if A59 also exhibited the same behavior.

**Comment by Vswe** [comment]
That bug was fixed in A53. For now, disconnect the pins before changing the pin amount. The error could however also be caused when moving things from/to groups. The error can only occur on dedicated servers.
