### ISSUE TITLE
while low signal on redstone trigger activates all the time

### ISSUE THREAD

**Issue by DrSilix** [Vswe/ModJam3#50]
the while low signal pin on the redstone trigger is broken, it seems to activate all the time.
to reproduce hook up 2 chests and a redstone receiver, input from one chest to another while low signal, with or without a signal it will trigger.

**Comment by Vswe** [comment]
The trigger is set to "If any", therefore if any of the sides have a low signal it will trigger. Set it to requires all or define the sides you're actually interested in.
