### ISSUE TITLE
Item Lookup - Gregtech

### ISSUE THREAD

**Issue by DarkDestry** [Vswe/ModJam3#64]
I cant seem to find items from gregtech such as purified crushed ore. I want to say its because of the huge metadata, such as those that extends into to 10000 and beyond, but i cant find a way to prove it. 

How about a way to integrate into NEI's item lookup or allow the user to enter item ID and Metadata?

**Comment by Vswe** [comment]
It only lists items that are visible in the creative inventory. If you want to access other items, simply have them in your inventory and search for ".inv".
