### ISSUE TITLE
Have groups have input and output

### ISSUE THREAD

**Issue by hvdklauw** [Vswe/ModJam3#69]
Would be cool if the groups have input and output so you can clean up big chunks of logic that have a single input and a single output.

When you zoom in on the group you basically get a output connector at the top of the screen and a input connector at the bottom.

When you zoom out the group has input and output connectors.

I think this will allow for better code organization.

**Comment by ppvolto** [comment]
Try nodes there have a input and output mode ;)

**Comment by hvdklauw** [comment]
Oh, thanks.. I will later today
