### ISSUE TITLE
Crafting/conditional feature request

### ISSUE THREAD

**Issue by the-creamster** [Vswe/ModJam3#74]
I've got a cobblegen and using SFM to automate the crafting of compressed cobble; of which i did last modpack(1.7.2), now i want to set it up again but the conditional command only triggers when its exactly that number, not greater than or equal to; which is what i would need it to be to accomplish my task at hand.

Any possibility of it becoming a improvement to a feature??

**Comment by Vswe** [comment]
It does check for equal or more.
