### ISSUE TITLE
Conditional/Autocrafter issue

### ISSUE THREAD

**Issue by the-creamster** [Vswe/ModJam3#75]
I may have not been clear enough in describing issue #74, so here is a better explanation with pictures of the commands. I want to autocraft all the compressed cobblestone variants, but only when there is a certain stock of the previous compressed/non compressed variant. The thing is I set the conditional for the 1x compressed autocrafter to 512(8 stacks) of cobble, but its not even crafting unless i connect the trigger directly to the input; and setting a precise amount to the input doesn't stop it from going past the desired stock threshold. Any ideas what i'm doing wrong??
![2014-10-31_10 21 53](https://cloud.githubusercontent.com/assets/2037833/4854746/7dc64e3e-6098-11e4-9d8f-c2c08899a1ae.png)
![2014-10-31_10 22 04](https://cloud.githubusercontent.com/assets/2037833/4854756/8622bc3e-6098-11e4-9b35-e7c70d3b264d.png)
![2014-10-31_10 22 33](https://cloud.githubusercontent.com/assets/2037833/4854754/86068104-6098-11e4-9b75-945b96d58b1e.png)
![2014-10-31_10 22 46](https://cloud.githubusercontent.com/assets/2037833/4854753/86055888-6098-11e4-9035-b85b7c180ec1.png)
![2014-10-31_10 23 24](https://cloud.githubusercontent.com/assets/2037833/4854755/86070a34-6098-11e4-996f-6ed56fa226cf.png)

**Comment by Vswe** [comment]
A barrel only contains a maximum of one stack at any given time (but if something tries to access it, it refills that stacks if there are more items stored than 64), that's why your setup doesn't work. There's nothing wrong with SFM.
