### ISSUE TITLE
Camouflage blocks retain their texture with Ztones blocks

### ISSUE THREAD

**Issue by GonzaloXavier** [Vswe/ModJam3#82]
Originally: https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/146
There's also no config in order to enable/disable certain blocks. That could be useful.

**Comment by GoryMoon** [comment]
I have tested this and the camouflage blocks do render the Ztones blocks correctly. Maybe update the Ztones version, I don't know what wrong but it's not SFM as it seams.
![Ztones Image](http://i.imgur.com/W8nBzki.png?1)

**Comment by GonzaloXavier** [comment]
Correct this somehow got fixed. Sorry for not reporting the fix.
