### ISSUE TITLE
Suggestion: Inventory Empty

### ISSUE THREAD

**Issue by MaelstromPhoenix** [Vswe/ModJam3#83]
First off, LOVE the mod. Started using it a few weeks ago and haven't stopped using it since (Goodbye item and fluid conduits :D). One thing I would love to see added is the ability to check if an inventory is empty, possibly in the condition statement. It would increase the possibilities of SFM by a lot and really help easily automate lots of tasks.

**Comment by Vswe** [comment]
It's possible, just check if there's not "any item" in a container.

**Comment by MaelstromPhoenix** [comment]
Wow I feel like an idiot now, I just got confused since it still shows the red exclamation mark on the condition statement. Thanks a lot!

**Comment by Vswe** [comment]
If it shows the red exclamation mark you haven't set it up properly.

**Comment by MaelstromPhoenix** [comment]
It shows me the exclamation mark because I don't have an item whitelisted or blacklisted for the "if any" condition. Still works though.

**Comment by MaelstromPhoenix** [comment]
It seems I may have jumped the gun a bit on getting it to work. Here is my setup:
![2015-03-02_12 10 18](https://cloud.githubusercontent.com/assets/11250511/6439669/40246b54-c0d5-11e4-97ac-3397dbf93b7c.png)
![2015-03-02_12 10 29](https://cloud.githubusercontent.com/assets/11250511/6439670/4042e52a-c0d5-11e4-9a3b-012ebec06741.png)

What I want it to do is to move items from Diamond Chest 1 (D1) to Diamond Chest 2 (D2) if D2 is empty. Currently it is moving _any_ items out of D1 into D2 when placed in, which means that the condition is always false, even when it has the red exclamation mark. As far as I know the "if any" statement and the exclamation mark aren't working properly without a white/blacklisted item. Any help is greatly appreciated.
